### ISSUE TITLE
Missing environment file

### ISSUE THREAD

**Issue by MrConstantine** [Mehonoshin/smartvpn-billing#101]
docker-compose -f docker-compose.development.yml build

ERROR: Couldn't find env file: /root/smartvpn-billing/.env

**Comment by trddddd** [comment]
you can create its file `touch .env` and put `SECRET_TOKEN` into .env
its 5 step https://github.com/Mehonoshin/smartvpn-billing#start-up-and-developing-with-docker

**Comment by Mehonoshin** [comment]
@MrConstantine feel free to reopen the issue, if you have any troubles with running the app.
