### ISSUE TITLE
New error during installation (docker compose)

### ISSUE THREAD

**Issue by MrConstantine** [Mehonoshin/smartvpn-billing#116]
Hello.
New bugs detected. They are associated with he ruby on rails. Not installed gems. 

Could not find aasm-5.0.1 in any of the sources

app_1       | Could not find aasm-5.0.1 in any of the sources
app_1       | Run `bundle install` to install missing gems.
app_1       | 09:28:49 web.1    | started with pid 13
app_1       | 09:28:49 worker.1 | started with pid 14
app_1       | 09:28:50 web.1    | bundler: failed to load command: rails (/usr/local/bundle/bin/rails)
app_1       | 09:28:50 web.1    | Bundler::GemNotFound: Could not find aasm-5.0.1 in any of the sources
app_1       | 09:28:50 web.1    |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:91:in `block in materialize'
app_1       | 09:28:50 web.1    |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `map!'
app_1       | 09:28:50 web.1    |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `materialize'
app_1       | 09:28:50 web.1    |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:170:in `specs'
app_1       | 09:28:50 web.1    |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:237:in `specs_for'
app_1       | 09:28:50 web.1    |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:226:in `requested_specs'
app_1       | 09:28:50 web.1    |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:108:in `block in definition_method'
app_1       | 09:28:50 web.1    |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:20:in `setup'
app_1       | 09:28:50 web.1    |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:107:in `setup'
app_1       | 09:28:50 worker.1 | bundler: failed to load command: sidekiq (/usr/local/bundle/bin/sidekiq)
app_1       | 09:28:50 web.1    |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `<top (required)>'
app_1       | 09:28:50 worker.1 | Bundler::GemNotFound: Could not find aasm-5.0.1 in any of the sources
app_1       | 09:28:50 web.1    |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
app_1       | 09:28:50 worker.1 |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:91:in `block in materialize'
app_1       | 09:28:50 web.1    |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
app_1       | 09:28:50 worker.1 |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `map!'
app_1       | 09:28:50 worker.1 |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `materialize'
app_1       | 09:28:50 worker.1 |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:170:in `specs'
app_1       | 09:28:50 worker.1 |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:237:in `specs_for'
app_1       | 09:28:50 worker.1 |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:226:in `requested_specs'
app_1       | 09:28:50 worker.1 |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:108:in `block in definition_method'
app_1       | 09:28:50 worker.1 |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:20:in `setup'
app_1       | 09:28:50 worker.1 |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:107:in `setup'
app_1       | 09:28:50 worker.1 |   /usr/local/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `<top (required)>'
app_1       | 09:28:50 worker.1 |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
app_1       | 09:28:50 worker.1 |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
app_1       | 09:28:50 web.1    | exited with code 1
app_1       | 09:28:50 system   | sending SIGTERM to all processes
app_1       | 09:28:50 worker.1 | exited with code 1

Docker error (I changed the version in the file to 2 and bypassed this error)

ERROR: Version in "./docker-compose.development.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by Mehonoshin** [comment]
@MrConstantine can you provide more information regarding the issue? Which command caused it?

**Comment by MrConstantine** [comment]
Yes. Command build - docker-compose -f docker-compose.development.yml up

**Comment by MrConstantine** [comment]
I can even give the SSH access to a virtual server. You will see that the build does not work. Problem in compatibility of gems versions

**Comment by Mehonoshin** [comment]
@MrConstantine if you are trying to run the app on VPS for production purposes, then docker-compose.development.yml is definitely not the right choice.
Production setup documentation is coming soon.

**Comment by Mehonoshin** [comment]
Lol, I see the reason. It downloads the image from docker hub https://github.com/Mehonoshin/smartvpn-billing/blob/master/docker-compose.development.yml#L22 instead of building it from scratch.
@trddddd Can you take a look at it?

**Comment by trddddd** [comment]
oh may, i fix it on the weekend

**Comment by trddddd** [comment]
fix) https://github.com/Mehonoshin/smartvpn-billing/pull/121
