### ISSUE TITLE
How can i install it?

### ISSUE THREAD

**Issue by itJunky** [Mehonoshin/smartvpn-billing#3]
How can i install it?
In docs install instruction is empty

**Comment by Mehonoshin** [comment]
@itJunky sorry for the silence. Do you still need help?

**Comment by itJunky** [comment]
Yeah

**Comment by Mehonoshin** [comment]
I guess we can dockerize them, for smooth up and running.
Probably make even a `docker-compose.yml` to run fast on a server.

**Comment by itJunky** [comment]
good if docker-compose.yml be attached to the project.

**Comment by Mehonoshin** [comment]
Sure, will do.
I believe we'll have it in the next two weeks since I'll have some time for that.

**Comment by Mehonoshin** [comment]
@itJunky just FYI the work is in progress in https://github.com/Mehonoshin/smartvpn-billing/pull/7
But still, there is a lot of remaining work to make the project up to date.

**Comment by MrMehdi** [comment]
tnx bro :+1:  :100:

**Comment by itJunky** [comment]
> @itJunky just FYI the work is in progress in #7
> But still, there is a lot of remaining work to make the project up to date.

Still have some problem with compose? Soon i'll try it.

**Comment by Mehonoshin** [comment]
@itJunky https://github.com/Mehonoshin/smartvpn/tree/master/setup#single-node
Compose works, now we need to create a detailed documentation :)

**Comment by itJunky** [comment]
ok, after check it, i can try to write some questions or answers for this documentation.

**Comment by Mehonoshin** [comment]
@itJunky sure, any information if useful for us

**Comment by Mehonoshin** [comment]
@itJunky feel free to open new issues if you have any troubles.
