### ISSUE TITLE
Tests sometimes are failures

### ISSUE THREAD

**Issue by araslanov-e** [Mehonoshin/smartvpn-billing#82]
https://travis-ci.org/Mehonoshin/smartvpn-billing/jobs/481815799

**Comment by reabiliti** [comment]
https://github.com/Mehonoshin/smartvpn-billing/pull/91

**Comment by Mehonoshin** [comment]
Should be solved at https://github.com/Mehonoshin/smartvpn-billing/pull/127/commits/fc14777024a79102661ef9d84bd4f3ca73e60e43

**Comment by Mehonoshin** [comment]
https://github.com/Mehonoshin/smartvpn-billing/pull/127/commits/b405c13b9835b7352b797072c8cba9eb75cbb680
