### ISSUE TITLE
Extract cron rake tasks into sidekiq jobs

### ISSUE THREAD

**Issue by Mehonoshin** [Mehonoshin/smartvpn-billing#93]
For example we have this job, that used to run via cron.
https://github.com/Mehonoshin/smartvpn-billing/blob/c3f043a2e8f9a4e885d3f685780d6c6d4113b516/lib/tasks/withdrawals.rake#L1

What we need now is to install clockwork, add it to Procfile and set it up to run this job once a day.

The detailed schedule, that used to be run via Cron is here https://github.com/Mehonoshin/smartvpn-billing/blob/c3f043a2e8f9a4e885d3f685780d6c6d4113b516/config/schedule.rb#L1

**Comment by ilyaerin** [comment]
@Mehonoshin is it important to use `clockwork`, or it's possible to change to https://github.com/jmettraux/rufus-scheduler? It looks more famous and powerful.

**Comment by Mehonoshin** [comment]
@ilyaerin up to you :) The main idea is to have some long-running lightweight process that can spawn sidekiq jobs on schedule. We don't want to use cron + rake combination, as it will start whole rails environment on every call, which can be long process that consumes a lot of resources.

**Comment by ilyaerin** [comment]
@Mehonoshin ok, thanks for the explanation.

**Comment by Mehonoshin** [comment]
https://github.com/Mehonoshin/smartvpn-billing/pull/113 just for history

**Comment by Mehonoshin** [comment]
Solved! Many thanks to @ilyaerin!
