### ISSUE TITLE
Extract email information into ENV

### ISSUE THREAD

**Issue by Mehonoshin** [Mehonoshin/smartvpn-billing#94]
https://github.com/Mehonoshin/smartvpn-billing/blob/master/config/environments/production.rb#L86

Here we have explicitly hardcoded smtp server, port and domain. We need to get rid of it in favor of configuration through the env variables.

**Comment by reabiliti** [comment]
https://github.com/Mehonoshin/smartvpn-billing/pull/105

**Comment by Mehonoshin** [comment]
Solved!
